#CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

### DISPLAY DONGLE OPTIONS
#CONFIG_ZMK_DISPLAY=y

### POWER OPTIONS
# La unidad del intervalo del informe de energía de la batería es segundos
#CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

### DEBUG OPTIONS
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

#CONFIG_ZMK_SLEEP=n
#CONFIG_PM_DEVICE=y
#CONFIG_ZMK_EXT_POWER=y

### SPLIT CENTRAL
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

### DISPLAY
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

### BATTERY FETCHING FROM HALVES
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

### WIDGETS
CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=y

### OPTIONAL
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_IDLE_TIMEOUT=60000